spring:
  application:
    name: local-deploy
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: root
    druid:
      initial-size: 3
      max-active: 20
      min-idle: 2
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: zg.yoyo.localdeploy.infrastructure.persistence
  configuration:
    map-underscore-to-camel-case: true

minio:
  endpoint: http://127.0.0.1:9000
  access-key: myadmin
  secret-key: myadmin123
  bucket: poc-bucket

logging:
  level:
    root: info
    com.baomidou.mybatisplus: info
    zg.yoyo.localdeploy: debug
    org.eclipse.paho.client.mqttv3: debug

server:
  port: 8083

# EMQX Configuration
emqx:
  broker: tcp://127.0.0.1:1883
  client-id: emqx-demo-client
  username: admin
  password: public
  topic: emqx/demo
  qos: 1
